
# Events settings
#worker process config
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 1024;
}

http {
	server {
		# SSL configuration
		listen 443 ssl;
		listen [::]:443 ssl;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_certificate /etc/nginx/ssl/nginx.crt;
		ssl_certificate_key /etc/nginx/ssl/nginx.key;

		server_name kbolon.42.fr;
		root /usr/share/nginx/html;

		# Add index.php to the list if you are using PHP
		index index.html;

		location / {
			try_files $uri $uri/ /index.html;
		}

		location /blog {
#			root /var/www/html;
			index index.php;
			try_files $uri $uri/ /index.php?$args;

			# pass PHP scripts to FastCGI server
			#
			location ~ \.php$ {
				include snippets/fastcgi-php.conf;
				fastcgi_pass wordpress:9000;
				fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
				include fastcgi_params;
				# With php-fpm (or other unix sockets):
				#fastcgi_pass unix:/run/php/php7.4-fpm.sock;
				# With php-cgi (or other tcp sockets):
				#fastcgi_pass 127.0.0.1:9000;
			}
		}

		location /admin {
			return 301 https://kbolon.42.fr/blog/wp-admin;
		}

		# Log settings
		access_log /var/log/nginx/access.log;
		error_log /var/log/nginx/error.log;
	}
}
