#specifies the Docker Compose file format version
version: '3.8'

services:
  nginx:
    container_name: my_nginx
    build:
      context: ./requirements/nginx
    env_file: .env
    depends_on:
      - wordpress
#      - mariadb
    ports:
      - 443:443
    image: my_nginx
    init: true
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped
    networks:
      my_inception:

  mariadb:
    container_name: my_mariadb
    build:
      context: ./requirements/mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_PASSWORD: ${DB_PASSWORD}
    image: my_mariadb
    init: true
    volumes:
      - maria_db:/var/lib/mysql
    networks:
      my_inception:
    ports:
     - 3306:3306

  wordpress:
    container_name: my_wp
    build:
      context: ./requirements/wordpress
    restart: unless-stopped
    image: my_wp
    init: true
    ports:
      - 9000:9000
    env_file: .env
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    volumes:
      - wordpress:/var/www/html
    networks:
      my_inception:

volumes:
  wordpress:
  maria_db:

networks:
  my_inception:



