services:
  nginx:
    build:
      context: ./requirements/nginx
    env_file: .env
    secrets:
      - key
      - crt
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - ${HOME_PATH}/data/wordpress:/var/www/html
    restart: unless-stopped
    networks:
      inception:
  mariadb:
    build:
      context: ../
      dockerfile: srcs/requirements/mariadb/Dockerfile
    secrets:
      - mdb_pw
      - mdb_root_pw
    restart: unless-stopped
    container_name: mariadb
    env_file: .env
    environment:
      MDB_PW: /run/secrets/mdb_pw
      MDB_ROOT_PW: /run/secrets/mdb_root_pw
    volumes:
      - ${HOME_PATH}/data/mariadb:/var/lib/mysql
    networks:
      inception:
    ports:
      - 3306:3306
  wordpress:
    container_name: wordpress
    build:
      context: ../
      dockerfile: srcs/requirements/wordpress/Dockerfile
    depends_on:
      - mariadb
    secrets:
      - mdb_pw
      - wp_admin_pw
      - wp_user_pw
    restart: unless-stopped
    ports:
      - 9000:9000
    env_file: .env
    environment:
      MDB_PW: /run/secrets/mdb_pw
      WP_ADMIN_PW: /run/secrets/wp_admin_pw
      WP_USER_PW: /run/secrets/wp_user_pw
    volumes:
      - ${HOME_PATH}/data/wordpress:/var/www/html
    networks:
      inception:

secrets:
  key:
    file: ${HOME_PATH}/Documents/Inception/secrets/nginx.key
  crt:
    file: ${HOME_PATH}/Documents/Inception/secrets/nginx.crt
  mdb_pw:
    file: ${HOME_PATH}/Documents/Inception/secrets/mdb_pw.txt
  mdb_root_pw:
    file: ${HOME_PATH}/Documents/Inception/secrets/mdb_root_pw.txt
  wp_admin_pw:
    file: ${HOME_PATH}/Documents/Inception/secrets/wp_admin_pw.txt
  wp_user_pw:
    file: ${HOME_PATH}/Documents/Inception/secrets/wp_user_pw.txt

networks:
  inception:
    driver: bridge
