services:
  nginx:
    build:
      context: ./requirements/nginx
    env_file: .env
    secrets:
      - key
      - crt
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    networks:
      inception:
  mariadb:
    build:
      context: ../
      dockerfile: srcs/requirements/mariadb/Dockerfile
    secrets:
      - mdb_pw
      - mdb_root_pw
    restart: unless-stopped
    container_name: mariadb
    env_file: .env
    environment:
      MDB_PW: /run/secrets/mdb_pw
      MDB_ROOT_PW: /run/secrets/mdb_root_pw
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      inception:
    ports:
      - 3306:3306
  wordpress:
    container_name: wordpress
    build:
      context: ../
      dockerfile: srcs/requirements/wordpress/Dockerfile
    depends_on:
      - mariadb
    secrets:
      - mdb_pw
      - wp_admin_pw
      - wp_user_pw
    restart: unless-stopped
    ports:
      - 9000:9000
    env_file: .env
    environment:
      MDB_PW: /run/secrets/mdb_pw
      WP_ADMIN_PW: /run/secrets/wp_admin_pw
      WP_USER_PW: /run/secrets/wp_user_pw
      WP_ADMIN_NAME: ${MDB_USER}
      WP_USER_NAME: ${WP_USER_NAME}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      inception:

secrets:
  key:
    file: /home/ubuntu/Documents/Inception/secrets/nginx.key
  crt:
    file: /home/ubuntu/Documents/Inception/secrets/nginx.crt
  mdb_pw:
    file: /home/ubuntu/Documents/Inception/secrets/mdb_pw.txt
  mdb_root_pw:
    file: /home/ubuntu/Documents/Inception/secrets/mdb_root_pw.txt
  wp_admin_pw:
    file: /home/ubuntu/Documents/Inception/secrets/wp_admin_pw.txt
  wp_user_pw:
    file: /home/ubuntu/Documents/Inception/secrets/wp_user_pw.txt

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/data/mariadb_data
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/data/wordpress_data